package frc.robot.util;

import edu.wpi.first.math.geometry.Translation2d;

// This class is autogenerated from avtrajopt/generateungeneratedtrajs.py. Do not edit.
public enum ArmvatorPosition {
  L1(new Translation2d(0.883106, 0.411799)),
  L2(new Translation2d(0.705416, 0.866083)),
  L3(new Translation2d(0.09825, 0.956759)),
  L4(new Translation2d(0.146098, 1.751568)),
  HP(new Translation2d(0.751075, 0.602371)),
  GROUND_INTAKE(new Translation2d(0.934147, 0.250304)),
  PROCESSOR(new Translation2d(0.508, 0.8)),
  NET(new Translation2d(0.0, 1.9419));

  public final Translation2d endeffPos;

  private ArmvatorPosition(Translation2d endeffPos) {
    this.endeffPos = endeffPos;
  }

  public static ArmvatorPosition getNearest(Translation2d endeffPos) {
    ArmvatorPosition best = null;
    double bestDist = Double.POSITIVE_INFINITY;
    for (ArmvatorPosition pos : ArmvatorPosition.values()) {
      double dist = pos.endeffPos.getDistance(endeffPos);
      if (dist < bestDist) {
        best = pos;
        bestDist = dist;
      }
    }
    return best;
  }
}
