package frc.robot.util;

import edu.wpi.first.math.geometry.Translation2d;

// This class is autogenerated from avtrajopt/generateungeneratedtrajs.py. Do not edit.
public enum ArmvatorPosition {
  L1(new Translation2d(0.732378, 0.662254)),
  L2(new Translation2d(0.66285, 0.833406)),
  L3(new Translation2d(0.103676, 1.009591)),
  L4(new Translation2d(0.160922, 1.839344)),
  AlgaeL3(new Translation2d(0.0, 1.07358)),
  AlgaeL2(new Translation2d(0.826348, 0.940281)),
  HP(new Translation2d(0.789204, 0.594708)),
  GROUND_INTAKE(new Translation2d(1.008151, 0.298628)),
  PROCESSOR(new Translation2d(0.85121, 0.500401)),
  NET(new Translation2d(0.0, 1.9673)),
  STOW(new Translation2d(0.636745, 0.758844));

  public final Translation2d endeffPos;

  private ArmvatorPosition(Translation2d endeffPos) {
    this.endeffPos = endeffPos;
  }

  public static ArmvatorPosition getNearest(Translation2d endeffPos) {
    ArmvatorPosition best = null;
    double bestDist = Double.POSITIVE_INFINITY;
    for (ArmvatorPosition pos : ArmvatorPosition.values()) {
      double dist = pos.endeffPos.getDistance(endeffPos);
      if (dist < bestDist) {
        best = pos;
        bestDist = dist;
      }
    }
    return best;
  }
}
